### ISSUE TITLE
don't know how to run this module 

### ISSUE THREAD

**Issue by t105362506** [kolban-google/sftp-gcs#18]
Hi !
Thanks for your package!

how to run this module to sftp some file to gcp bucket

reviewed this document but don't know how to run with it

if that have a example it great, Thank you

**Comment by kolban-google** [comment]
Please have a look at https://medium.com/google-cloud/sftp-access-to-google-cloud-storage-43ffd6134b0e

Lets see if this helps ... it contains a video showing it being used.  Let us know if this assists.
